NKL.Lession03/NKL.Lession03/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NKL.Lession03.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

NKL.Lession03/NKL.Lession03/Controllers/NKLStudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NKL.Lession03.Controllers
{
    public class NKLStudentController : Controller
    {
        // GET: NKLStudent
        public ActionResult Index()
        {
            //Du lieu tu view Data
            ViewData["msg"] = "View Data - Nguyen Khanh Linh";
            ViewData["time"] = DateTime.Now.ToString("hh:mm:ss dd/MM/yyyy tt");    
            return View();
        }

        public ActionResult StuudentList()
        {
            //sd view bag
            //luu tru gia tri don
            ViewBag.titleName = "Danh sach hoc vien - Nguyen Khanh Linh";

            //Gia tri la mot tap hop
            string[] names = { "Linh","phuc","nam"};
            ViewBag.list=names;

            //gia tri la mot doi tuong
            var ojb = new
            {
                ID = 100,
                Name = "Linh",
                Age = 19
            };
            ViewBag.student = ojb;
            return View();
        }

        public ActionResult Insert()
        {
            return View("AddStudent");
        }
    }
}

NKL.Lession03/NKL.Lession03/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</main>

NKL.Lession03/NKL.Lession03/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

NKL.Lession03/NKL.Lession03/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<main>
    <section class="row" aria-labelledby="aspnetTitle">
        <h1 id="title">ASP.NET</h1>
        <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
        <p><a href="https://asp.net" class="btn btn-primary btn-md">Learn more &raquo;</a></p>
    </section>

    <div class="row">
        <section class="col-md-4" aria-labelledby="gettingStartedTitle">
            <h2 id="gettingStartedTitle">Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="librariesTitle">
            <h2 id="librariesTitle">Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="hostingTitle">
            <h2 id="hostingTitle">Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </section>
    </div>
</main>

NKL.Lession03/NKL.Lession03/Views/NKLStudent/AddStudent.cshtml
@{
    ViewBag.Title = "AddStudent";
}

<h2>Form</h2>
@{ Html.BeginForm("Insert", "NKLStudent");}
@Html.Label("MSV");
@Html.TextBox("Name", "Linh");

@{ Html.EndForm();}
@{ 
        int[] names = { 10, 30, 22, 23, 23 };
}
@foreach (var item in names)
{
    <li>@item</li>
}

NKL.Lession03/NKL.Lession03/Views/NKLStudent/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Pham mem quan li sinh vien</h2>
<h3>@ViewData["msg"]</h3>
<h3>Bay gio la: @ViewData["time"]</h3>

NKL.Lession03/NKL.Lession03/Views/NKLStudent/StuudentList.cshtml
@{
    ViewBag.Title = "StuudentList";
}

<h2>@ViewBag.titleName</h2>
<hr />
@foreach (var item in ViewBag.list)
{
    <h5>@item</h5>
}
<hr />
<h2>Thong tin sinh vien</h2>
@ViewBag.student;

@Html.Partial("_ViewContact")

NKL.Lession03/NKL.Lession03/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
            @Html.Partial("_ViewContact")
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

NKL.Lession03/NKL.Lession03/Views/Shared/_ViewContact.cshtml
@{
    ViewBag.Title = "_ViewContact";
}

<h2>Thong tin SV</h2>
<p>MSV: 2210900035</p>
<p>Name: Nguyen Khanh Linh</p>